### ISSUE TITLE
"You have scored X points this round!" shows previous round score

### ISSUE THREAD

**Issue by Caster** [blinry/wikidata-guessr#1]
After making a guess, the dialog showing the guessed and actual locations displays the score of the previous round, not the current one. It is only possible to see your score by looking at the *Last Round Score" in the lower left corner after dismissing the dialog.

It's a fun game by the way!

**Comment by blinry** [comment]
Fixed in 04b2b58. Thanks for reporting these, Thom! Keep 'em coming in case you spot something else!
